---
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.5
before_install: gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  email: false
env:
  global:
    - secure: ej6WHUww4mqBmHDh/P2EJM0Y7aPd+rLZGmB8ToL5qs7u+G8o3vohI+fZWpRRzs1rKeRsWLiARNGx8iU7v7dsWiEMgB4Cr+hEIlNi8Ga3IATdZIT0bbdO2+KGlGkBFezAVjmWJnGz2/8QLYvfRoLLNEFDDiA5TzU4W7y8xMc4JWbYb14TZ/Du9ZA7OOzOaVxAUAoDpUBmB35NGx77G4ceovS91mWqb5sOxtdHJOD5lGs3sOOqqB7niqcMijBz/hiV1YizwmnNj4N8YzUfqZRy1bQyjijQaYaY/+NozOhiYworfOjsFMu5PkZZHOtr8nMk9XwvHTghiQpd94Eubov993YcNFtKH0V4BhzFPA+o6QscmPHnRytX+neljM+pUiXkZUvi8uMgrCc7eTq225w6z21T+Xgh6T7Bs+vix+k3uDrnGWg1q2ZbvP+CiD3jjdpvBa4jf9c/ubqAtvvdPjfuyfY2JhKnh6WS2qDUTtRWX4RZlIR6PrYuD+vm6dYWaAsofrsNJiahCAyZqfWmyZ30NaOSY3GF/PQnRW98bIgjj0RJnWBe6lS30fEePTvk9GC/j1QfiY5q6uokImQ8Sd5CgJrJNesKuXyE83DSvrAEvCNenr42fOdrTfPeK044RqHb/2POvLlL0c+u7xuHvh+KwaEYo1+8Pc4qV3Nvhknk6kw=
